name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "0 0 * * *"

jobs:
  stale:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/stale@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'Your issue is stale, thats bad!'
        stale-pr-message: 'Your PR has been stale from a lot of time!'
        stale-issue-label: 'no-issue-activity'
        stale-pr-label: 'no-pr-activity'
